/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CreditCardRadioButton = new javax.swing.JRadioButton();
        InstapayRadioButton = new javax.swing.JRadioButton();
        CashOnDeliveryRadioButton = new javax.swing.JRadioButton();
        ContinueToCheckoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Payment");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Choose Payment Method");

        CreditCardRadioButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CreditCardRadioButton.setText("Credit Card");
        CreditCardRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditCardRadioButtonActionPerformed(evt);
            }
        });

        InstapayRadioButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        InstapayRadioButton.setText("InstaPay");

        CashOnDeliveryRadioButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CashOnDeliveryRadioButton.setText("Cash On Delivery");

        ContinueToCheckoutButton.setBackground(new java.awt.Color(51, 153, 255));
        ContinueToCheckoutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ContinueToCheckoutButton.setText("Continue To Checkout");
        ContinueToCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueToCheckoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InstapayRadioButton)
                            .addComponent(CreditCardRadioButton)
                            .addComponent(CashOnDeliveryRadioButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(ContinueToCheckoutButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel2)))
                .addContainerGap(598, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(CreditCardRadioButton)
                .addGap(28, 28, 28)
                .addComponent(InstapayRadioButton)
                .addGap(18, 18, 18)
                .addComponent(CashOnDeliveryRadioButton)
                .addGap(37, 37, 37)
                .addComponent(ContinueToCheckoutButton)
                .addGap(0, 182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreditCardRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditCardRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditCardRadioButtonActionPerformed

    private void ContinueToCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueToCheckoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinueToCheckoutButtonActionPerformed
private void CashOnDeliveryRadioButton(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }     
private void InstapayRadioButton(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    } 


 
    public JButton getContinueToCheckoutButton() {
        return ContinueToCheckoutButton;
    }
    
      public JRadioButton getCashOnDeliveryRadioButton() {
        return CashOnDeliveryRadioButton;
    }
      
        public JRadioButton getCreditCardRadioButton() {
        return CreditCardRadioButton;
    }
        
          public JRadioButton getInstapayRadioButton() {
        return InstapayRadioButton;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CashOnDeliveryRadioButton;
    private javax.swing.JButton ContinueToCheckoutButton;
    private javax.swing.JRadioButton CreditCardRadioButton;
    private javax.swing.JRadioButton InstapayRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
